name: Plan Terraform changes
on:
  workflow_call:
    inputs:
      concurrency_group:
        required: false
        type: string
        default: 'create-plan-${{ github.ref }}'
      run_name:
        required: false
        type: string
        default: 'Plan Terraform changes - ${{ github.ref }}'
      runs_on:
        required: false
        type: string
        default: 'ubuntu-22.04'
      environment:
        required: true
        type: string
      gcp_sa_email:
        required: true
        type: string
      gcp_wif_resource_id:
        required: true
        type: string
      gcp_token_lifetime:
        required: false
        type: string
        default: '300s'

concurrency:
  group: ${{ inputs.concurrency_group }}
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    env:
      ENVIRONMENT: ${{ inputs.environment }}
    name: Plan Terraform changes
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Bootstrap repository
        uses: ./.github/actions/bootstrap-repository
      - name: Login to GCP
        uses: google-github-actions/auth@v3
        id: gcp_auth
        with:
          export_environment_variables: 'true'
          workload_identity_provider: ${{ inputs.gcp_wif_resource_id }}
          service_account: ${{ inputs.gcp_sa_email }}
          access_token_lifetime: ${{ inputs.gcp_token_lifetime }}
      - name: Retrieve TF Cloud credentials
        uses: ./.github/actions/terraform-cloud-login
        id: tf_cloud_login
      - name: Run Terraform plan
        uses: ./.github/actions/terraform-plan
        id: plan
        env:
          TF_TOKEN_app_terraform_io: ${{ steps.tf_cloud_login.outputs.terraform_cloud_api_token }}
          ENVIRONMENT: ${{ inputs.environment }}
        with:
          environment: ${{ inputs.environment }}